./testSA ABRACADABRA! ARD!RCAAAABB
./testSA SIX.MIXED.PIXIES.SIFT.SIXTY.PIXIE.DUST.BOXES TEXDYST.E.IXXIIXXSSMPPS.B..EE.S.UFSXDIIOIIIT
#./testLCP acaaacatatz 0 2 1 3 1 2 0 2 0 1 0
./testSA mmiissiissiippii ipsmsiiimipissii
./fastTime FP.LOG
